/* Generated by Cython 3.0.10 */

#ifndef __PYX_HAVE__nachbagauer3Dc
#define __PYX_HAVE__nachbagauer3Dc

#include "Python.h"
struct c_PyObj;

/* "nachbagauer3Dc.pyx":36
 * #         3D NODE                                                             %
 * #%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
 * cdef public class node[object c_PyObj, type c_PyObj_t]:             # <<<<<<<<<<<<<<
 *     """
 *     finite element node with nine dof
 */
struct c_PyObj {
  PyObject_HEAD
  double q0[9];
  double q[9];
  double u0[9];
  double u[9];
  long globalDof[9];
  PyObject *name;
  PyObject *marker;
};

#ifndef __PYX_HAVE_API__nachbagauer3Dc

#ifdef CYTHON_EXTERN_C
    #undef __PYX_EXTERN_C
    #define __PYX_EXTERN_C CYTHON_EXTERN_C
#elif defined(__PYX_EXTERN_C)
    #ifdef _MSC_VER
    #pragma message ("Please do not define the '__PYX_EXTERN_C' macro externally. Use 'CYTHON_EXTERN_C' instead.")
    #else
    #warning Please do not define the '__PYX_EXTERN_C' macro externally. Use 'CYTHON_EXTERN_C' instead.
    #endif
#else
    #define __PYX_EXTERN_C extern "C++"
#endif

#ifndef DL_IMPORT
  #define DL_IMPORT(_T) _T
#endif

__PYX_EXTERN_C DL_IMPORT(PyTypeObject) c_PyObj_t;

#endif /* !__PYX_HAVE_API__nachbagauer3Dc */

/* WARNING: the interface of the module init function changed in CPython 3.5. */
/* It now returns a PyModuleDef instance instead of a PyModule instance. */

#if PY_MAJOR_VERSION < 3
PyMODINIT_FUNC initnachbagauer3Dc(void);
#else
/* WARNING: Use PyImport_AppendInittab("nachbagauer3Dc", PyInit_nachbagauer3Dc) instead of calling PyInit_nachbagauer3Dc directly from Python 3.5 */
PyMODINIT_FUNC PyInit_nachbagauer3Dc(void);

#if PY_VERSION_HEX >= 0x03050000 && (defined(__GNUC__) || defined(__clang__) || defined(_MSC_VER) || (defined(__cplusplus) && __cplusplus >= 201402L))
#if defined(__cplusplus) && __cplusplus >= 201402L
[[deprecated("Use PyImport_AppendInittab(\"nachbagauer3Dc\", PyInit_nachbagauer3Dc) instead of calling PyInit_nachbagauer3Dc directly.")]] inline
#elif defined(__GNUC__) || defined(__clang__)
__attribute__ ((__deprecated__("Use PyImport_AppendInittab(\"nachbagauer3Dc\", PyInit_nachbagauer3Dc) instead of calling PyInit_nachbagauer3Dc directly."), __unused__)) __inline__
#elif defined(_MSC_VER)
__declspec(deprecated("Use PyImport_AppendInittab(\"nachbagauer3Dc\", PyInit_nachbagauer3Dc) instead of calling PyInit_nachbagauer3Dc directly.")) __inline
#endif
static PyObject* __PYX_WARN_IF_PyInit_nachbagauer3Dc_INIT_CALLED(PyObject* res) {
  return res;
}
#define PyInit_nachbagauer3Dc() __PYX_WARN_IF_PyInit_nachbagauer3Dc_INIT_CALLED(PyInit_nachbagauer3Dc())
#endif
#endif

#endif /* !__PYX_HAVE__nachbagauer3Dc */
