/* Generated by Cython 0.29.24 */

#ifndef __PYX_HAVE__helper_funcs
#define __PYX_HAVE__helper_funcs

#include "Python.h"

#ifndef __PYX_HAVE_API__helper_funcs

#ifndef __PYX_EXTERN_C
  #ifdef __cplusplus
    #define __PYX_EXTERN_C extern "C"
  #else
    #define __PYX_EXTERN_C extern
  #endif
#endif

#ifndef DL_IMPORT
  #define DL_IMPORT(_T) _T
#endif

__PYX_EXTERN_C PyObject *getUnitaryVector(__Pyx_memviewslice);

#endif /* !__PYX_HAVE_API__helper_funcs */

/* WARNING: the interface of the module init function changed in CPython 3.5. */
/* It now returns a PyModuleDef instance instead of a PyModule instance. */

#if PY_MAJOR_VERSION < 3
PyMODINIT_FUNC inithelper_funcs(void);
#else
PyMODINIT_FUNC PyInit_helper_funcs(void);
#endif

#endif /* !__PYX_HAVE__helper_funcs */
