/* Generated by Cython 0.29.24 */

#ifndef __PYX_HAVE__nachbagauer3Dc
#define __PYX_HAVE__nachbagauer3Dc

#include "Python.h"
struct c_PyObj;

/* "nachbagauer3Dc.pyx":32
 * #         3D NODE                                                             %
 * #%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
 * cdef public class node[object c_PyObj, type c_PyObj_t]:             # <<<<<<<<<<<<<<
 * 
 *     cdef double [9] q0
 */
struct c_PyObj {
  PyObject_HEAD
  double q0[9];
  double q[9];
  double u0[9];
  double u[9];
  long globalDof[9];
  PyObject *name;
  PyObject *marker;
};

#ifndef __PYX_HAVE_API__nachbagauer3Dc

#ifndef __PYX_EXTERN_C
  #ifdef __cplusplus
    #define __PYX_EXTERN_C extern "C"
  #else
    #define __PYX_EXTERN_C extern
  #endif
#endif

#ifndef DL_IMPORT
  #define DL_IMPORT(_T) _T
#endif

__PYX_EXTERN_C DL_IMPORT(PyTypeObject) c_PyObj_t;

#endif /* !__PYX_HAVE_API__nachbagauer3Dc */

/* WARNING: the interface of the module init function changed in CPython 3.5. */
/* It now returns a PyModuleDef instance instead of a PyModule instance. */

#if PY_MAJOR_VERSION < 3
PyMODINIT_FUNC initnachbagauer3Dc(void);
#else
PyMODINIT_FUNC PyInit_nachbagauer3Dc(void);
#endif

#endif /* !__PYX_HAVE__nachbagauer3Dc */
